# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ba679c38-3e54-4017-9a3e-90876c9659ee";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AD87-06E4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/nextcloud" =
    { device = "nextcloud:media";
      fsType = "fuse.rclone";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/aac9ed38-abcb-486b-ae98-d32870e57fb5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
