name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        # Configure Nix to enable flakes
        extra_nix_config: |
          experimental-features = nix-command flakes
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    # Update
    - run: nix flake update --commit-lock-file
    # Run the general flake checks
    - run: nix flake check
    # PR
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
    
    
